name: brent-oil
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.1.4
  - numpy=1.26.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - jupyter=1.0.0
  - scipy=1.11.4
  - statsmodels=0.14.1
  - yfinance=0.2.28
  - pymc=5.10.0
  - arviz=0.17.0
  - flask=3.0.0
  - pytest=7.4.3